services:
  - type: web
    name: storybook-app
    env: python
    region: oregon
    plan: free

    buildCommand: |
      apt-get update && apt-get install -y ffmpeg git-lfs && \
      git lfs install && \
      pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
